-- MySQL Script generated by MySQL Workbench
-- 12/09/15 10:24:00
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Mahasiswa`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Mahasiswa` (
  `NIM` INT NOT NULL,
  `nama_Mahasiswa` VARCHAR(45) NOT NULL,
  `pswd_Mahasiswa` VARCHAR(25) NOT NULL,
  PRIMARY KEY (`NIM`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departemen`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departemen` (
  `id_Departemen` INT NOT NULL,
  `nama_Departemen` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Departemen`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Administrator`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Administrator` (
  `user_Admin` VARCHAR(25) NOT NULL,
  `nama_Admin` VARCHAR(45) NOT NULL,
  `pswd_Admin` VARCHAR(45) NOT NULL,
  `departemen_Admin` VARCHAR(45) NOT NULL,
  `Departemen_id_Departemen` INT NOT NULL,
  PRIMARY KEY (`user_Admin`),
  INDEX `fk_Administrator_Departemen1_idx` (`Departemen_id_Departemen` ASC),
  CONSTRAINT `fk_Administrator_Departemen1`
    FOREIGN KEY (`Departemen_id_Departemen`)
    REFERENCES `mydb`.`Departemen` (`id_Departemen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`KategoriLapor`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`KategoriLapor` (
  `id_KategoriLapor` INT NOT NULL,
  `nama_KategoriLapor` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_KategoriLapor`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Pelaporan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Pelaporan` (
  `id_Pelaporan` INT NOT NULL,
  `isi_Pelaporan` TEXT(450) NOT NULL,
  `tgl_Pelaporan` DATE NOT NULL,
  `Mahasiswa_NIM` INT NOT NULL,
  `KategoriLapor_id_KategoriLapor` INT NOT NULL,
  PRIMARY KEY (`id_Pelaporan`),
  INDEX `fk_Pelaporan_Mahasiswa_idx` (`Mahasiswa_NIM` ASC),
  INDEX `fk_Pelaporan_KategoriLapor1_idx` (`KategoriLapor_id_KategoriLapor` ASC),
  CONSTRAINT `fk_Pelaporan_Mahasiswa`
    FOREIGN KEY (`Mahasiswa_NIM`)
    REFERENCES `mydb`.`Mahasiswa` (`NIM`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Pelaporan_KategoriLapor1`
    FOREIGN KEY (`KategoriLapor_id_KategoriLapor`)
    REFERENCES `mydb`.`KategoriLapor` (`id_KategoriLapor`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Tanggapan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Tanggapan` (
  `id_Tanggapan` INT NOT NULL,
  `isi_Tanggapan` TEXT(450) NOT NULL,
  `tgl_Tanggapan` DATE NOT NULL,
  `Administrator_user_Admin` VARCHAR(25) NOT NULL,
  `Pelaporan_id_Pelaporan` INT NOT NULL,
  PRIMARY KEY (`id_Tanggapan`),
  INDEX `fk_Tanggapan_Administrator1_idx` (`Administrator_user_Admin` ASC),
  INDEX `fk_Tanggapan_Pelaporan1_idx` (`Pelaporan_id_Pelaporan` ASC),
  CONSTRAINT `fk_Tanggapan_Administrator1`
    FOREIGN KEY (`Administrator_user_Admin`)
    REFERENCES `mydb`.`Administrator` (`user_Admin`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Tanggapan_Pelaporan1`
    FOREIGN KEY (`Pelaporan_id_Pelaporan`)
    REFERENCES `mydb`.`Pelaporan` (`id_Pelaporan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Departemen_has_Pelaporan`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `mydb`.`Departemen_has_Pelaporan` (
  `Departemen_id_Departemen` INT NOT NULL,
  `Pelaporan_id_Pelaporan` INT NOT NULL,
  PRIMARY KEY (`Departemen_id_Departemen`, `Pelaporan_id_Pelaporan`),
  INDEX `fk_Departemen_has_Pelaporan_Pelaporan1_idx` (`Pelaporan_id_Pelaporan` ASC),
  INDEX `fk_Departemen_has_Pelaporan_Departemen1_idx` (`Departemen_id_Departemen` ASC),
  CONSTRAINT `fk_Departemen_has_Pelaporan_Departemen1`
    FOREIGN KEY (`Departemen_id_Departemen`)
    REFERENCES `mydb`.`Departemen` (`id_Departemen`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Departemen_has_Pelaporan_Pelaporan1`
    FOREIGN KEY (`Pelaporan_id_Pelaporan`)
    REFERENCES `mydb`.`Pelaporan` (`id_Pelaporan`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
